import { BuildingType } from '../_enums/BuildingType';

export const buildingNames: Record<BuildingType, string> = Object.freeze({
  [BuildingType.None]: 'Building site',
  [BuildingType.Wood]: 'Woodcutter',
  [BuildingType.Clay]: 'Clay Pit',
  [BuildingType.Iron]: 'Iron Mine',
  [BuildingType.Crop]: 'Cropland',
  [BuildingType.Sawmill]: 'Sawmill',
  [BuildingType.Brickyard]: 'Brickyard',
  [BuildingType.IronFoundry]: 'Iron Foundry',
  [BuildingType.GrainMill]: 'Grain Mill',
  [BuildingType.Bakery]: 'Bakery',
  [BuildingType.Warehouse]: 'Warehouse',
  [BuildingType.Granary]: 'Granary',
  [BuildingType.Blacksmith]: 'Blacksmith',
  [BuildingType.Smithy]: 'Smithy',
  [BuildingType.TournamentSquare]: 'Tournament Square',
  [BuildingType.MainBuilding]: 'Main Building',
  [BuildingType.RallyPoint]: 'Rally Point',
  [BuildingType.Marketplace]: 'Marketplace',
  [BuildingType.Embassy]: 'Embassy',
  [BuildingType.Barracks]: 'Barracks',
  [BuildingType.Stable]: 'Stable',
  [BuildingType.Workshop]: 'Workshop',
  [BuildingType.Academy]: 'Academy',
  [BuildingType.Cranny]: 'Cranny',
  [BuildingType.TownHall]: 'Town Hall',
  [BuildingType.Residence]: 'Residence',
  [BuildingType.Palace]: 'Palace',
  [BuildingType.Treasury]: 'Treasury',
  [BuildingType.TradeOffice]: 'Trade Office',
  [BuildingType.GreatBarracks]: 'Great Barracks',
  [BuildingType.GreatStable]: 'Great Stable',
  [BuildingType.CityWall]: 'City Wall',
  [BuildingType.EarthWall]: 'Earth Wall',
  [BuildingType.Palisade]: 'Palisade',
  [BuildingType.StonemasonsLodge]: 'Stonemason\'s Lodge',
  [BuildingType.Brewery]: 'Brewery',
  [BuildingType.Trapper]: 'Trapper',
  [BuildingType.HerosMansion]: 'Hero\'s Mansion',
  [BuildingType.GreatWarehouse]: 'Great Warehouse',
  [BuildingType.GreatGranary]: 'Great Granary',
  [BuildingType.WonderOfTheWorld]: 'Wonder of the World',
  [BuildingType.HorseDrinkingTrough]: 'Horse Drinking Trough',
  [BuildingType.StoneWall]: 'Stone Wall',
  [BuildingType.CommandCenter]: 'Command Center',
  [BuildingType.MakeshiftWall]: 'Makeshift Wall',
  [BuildingType.Waterworks]: 'Waterworks',
});
