export enum BotEvent {
  ActiveVillageIdChanged = 'ActiveVillageIdChanged',
  BotRunningChanged = 'BotRunningChanged',
  BuildingsInProgressUpdated = 'BuildingsInProgressUpdated',
  BuildingSpotsUpdated = 'BuildingSpotsUpdated',
  CrannyCapacityUpdated = 'CrannyCapacityUpdated',
  HeroInformationUpdated = 'HeroInformationUpdated',
  LogEntryAdded = 'LogEntryAdded',
  NextTaskExecutionChanged = 'NextTaskExecutionChanged',
  NextTasksExecutionChanged = 'NextTasksExecutionChanged',
  NextVillageTaskExecutionChanged = 'NextVillageTaskExecutionChanged',
  QueuedUpdated = 'QueueUpdated',
  VillageUpdated = 'VillageUpdated',
  VillagesUpdated = 'VillagesUpdated',
}