/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { ApiContext } from "./apiContext.type"
import { AutoAcademySettings } from "./../_models/settings/tasks/autoAcademySettings"
import { AutoSmithySettings, AutoSmithyUnitSettings } from "./../_models/settings/tasks/autoSmithySettings"
import { BuildingInProgress } from "./../_models/buildings/inProgress/buildingInProgress"
import { BuildingQueue } from "./../_models/buildings/queue/buildingQueue"
import { BuildingSpot } from "./../_models/buildings/spots/buildingSpot"
import { GeneralVillageSettings } from "./../_models/settings/generalVillageSettings"
import { Hero } from "./../_models/hero/hero"
import { QueuedBuilding } from "./../_models/buildings/queue/queuedBuilding"
import { Resources } from "./../_models/misc/resources"
import { TextLogEntryContent } from "./../_models/logs/content/text"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AccountInput: { // input type
    password: string; // String!
    server: string; // String!
    username: string; // String!
  }
  AutoAcademySettingsInput: { // input type
    allow: boolean; // Boolean!
    coolDown: NexusGenInputs['CoolDownInput']; // CoolDownInput!
    useHeroResources: boolean; // Boolean!
  }
  AutoSmithySettingsInput: { // input type
    allow: boolean; // Boolean!
    coolDown: NexusGenInputs['CoolDownInput']; // CoolDownInput!
    useHeroResources: boolean; // Boolean!
  }
  AvailableNewBuildingsInput: { // input type
    fieldId: number; // Int!
    villageId: string; // ID!
  }
  CoolDownInput: { // input type
    max: NexusGenInputs['DurationInput']; // DurationInput!
    min: NexusGenInputs['DurationInput']; // DurationInput!
  }
  DequeueBuildingAtFieldInput: { // input type
    fieldId: number; // Int!
    targetLevel?: number | null; // Int
    villageId: string; // ID!
  }
  DequeueBuildingInput: { // input type
    level?: number | null; // Int
    queueId: string; // ID!
    villageId: string; // ID!
  }
  DualQueueSettingsInput: { // input type
    allow: boolean; // Boolean!
    preference: NexusGenEnums['DualQueuePreference']; // DualQueuePreference!
  }
  DurationInput: { // input type
    days: number; // Int!
    hours: number; // Int!
    minutes: number; // Int!
    seconds: number; // Int!
  }
  EnqueueBuildingInput: { // input type
    addNewToTop: boolean; // Boolean!
    fieldId: number; // Int!
    targetLevel?: number | null; // Int
    type: number; // Int!
    villageId: string; // ID!
  }
  GlobalAutoBuildSettingsInput: { // input type
    allow: boolean; // Boolean!
    videoFeature: NexusGenInputs['VideoFeatureSettingsInput']; // VideoFeatureSettingsInput!
  }
  HeroLevelUpItemInput: { // input type
    defBonus: number; // Int!
    name: string; // String!
    offBonus: number; // Int!
    offensiveStrength: number; // Int!
    resources: number; // Int!
  }
  SearchMapInput: { // input type
    cropBonus: number; // Int!
    origin: NexusGenInputs['SearchMapOriginInput']; // SearchMapOriginInput!
    types: string[]; // [String!]!
  }
  SearchMapOriginInput: { // input type
    radius: number; // Int!
    x: number; // Int!
    y: number; // Int!
  }
  TimestampInput: { // input type
    totalSeconds: number; // Int!
  }
  UpdateAccountSettingsInput: { // input type
    allowTasks: boolean; // Boolean!
    autoAcademy: boolean; // Boolean!
    autoBuild: NexusGenInputs['GlobalAutoBuildSettingsInput']; // GlobalAutoBuildSettingsInput!
    autoParty: boolean; // Boolean!
    autoSmithy: boolean; // Boolean!
    autoUnits: boolean; // Boolean!
    tasksCoolDown: NexusGenInputs['CoolDownInput']; // CoolDownInput!
  }
  UpdateAutoAdventureSettingsInput: { // input type
    adventureCriteria: NexusGenEnums['AdventureCriteria']; // AdventureCriteria!
    allow: boolean; // Boolean!
    coolDown: NexusGenInputs['CoolDownInput']; // CoolDownInput!
    hardMinHealth: number; // Int!
    maxTravelTime: NexusGenInputs['DurationInput']; // DurationInput!
    normalMinHealth: number; // Int!
    preferHard: boolean; // Boolean!
  }
  UpdateAutoBuildSettingsInput: { // input type
    allow: boolean; // Boolean!
    autoCropFields: boolean; // Boolean!
    autoStorage: NexusGenInputs['UpdateAutoStorageSettingsInput']; // UpdateAutoStorageSettingsInput!
    coolDown: NexusGenInputs['CoolDownInput']; // CoolDownInput!
    dualQueue: NexusGenInputs['DualQueueSettingsInput']; // DualQueueSettingsInput!
    minCrop: number; // Int!
    useHeroResources: boolean; // Boolean!
  }
  UpdateAutoMentorSettingsInput: { // input type
    acceptDailyRewards: boolean; // Boolean!
    acceptTaskRewards: boolean; // Boolean!
  }
  UpdateAutoPartySettingsInput: { // input type
    allowLarge: boolean; // Boolean!
    allowSmall: boolean; // Boolean!
    coolDown: NexusGenInputs['CoolDownInput']; // CoolDownInput!
    minCulturePointsLarge: number; // Int!
    minCulturePointsSmall: number; // Int!
    useHeroResources: boolean; // Boolean!
  }
  UpdateAutoStorageOptionSettingsInput: { // input type
    allow: boolean; // Boolean!
    overflowLevel: number; // Int!
  }
  UpdateAutoStorageSettingsInput: { // input type
    allowFreeSpots: boolean; // Boolean!
    granary: NexusGenInputs['UpdateAutoStorageOptionSettingsInput']; // UpdateAutoStorageOptionSettingsInput!
    warehouse: NexusGenInputs['UpdateAutoStorageOptionSettingsInput']; // UpdateAutoStorageOptionSettingsInput!
  }
  UpdateAutoUnitsBuildingSettingsInput: { // input type
    allow: boolean; // Boolean!
    maxBuildTime: NexusGenInputs['DurationInput']; // DurationInput!
  }
  UpdateAutoUnitsSettingsInput: { // input type
    allow: boolean; // Boolean!
    coolDown: NexusGenInputs['CoolDownInput']; // CoolDownInput!
    minCrop: number; // Int!
    useHeroResources: boolean; // Boolean!
  }
  UpdateAutoUnitsUnitSettingsInput: { // input type
    autoBuild: boolean; // Boolean!
    index: number; // Int!
    targetAmount: number; // Int!
    trainForever: boolean; // Boolean!
  }
  UpdateGeneralSettingsInput: { // input type
    autoStart: boolean; // Boolean!
    chromePath: string; // String!
    headlessChrome: boolean; // Boolean!
  }
  UpdateGeneralVillageSettingsInput: { // input type
    allowTasks: boolean; // Boolean!
  }
  VideoFeatureSettingsInput: { // input type
    allow: boolean; // Boolean!
    minBuildTime: NexusGenInputs['DurationInput']; // DurationInput!
  }
}

export interface NexusGenEnums {
  AdventureCriteria: "Closest" | "Furthest" | "Random"
  BotState: "InitialScanning" | "None" | "Paused" | "Running" | "Stopping"
  BuildingState: "Completed" | "None" | "OngoingMaxed" | "QueueMaxed"
  ClaimHeroResourcesReason: "AutoAcademy" | "AutoBuild" | "AutoParty" | "AutoSmithy" | "AutoUnits"
  DualQueuePreference: "Infrastructure" | "Resources"
  HeroState: "Dead" | "InVillage" | "Moving" | "Reviving" | "Unknown"
  MapSearchState: "None" | "Scanning" | "Searching"
  TaskType: "AutoAcademy" | "AutoAdventure" | "AutoBuild" | "AutoParty" | "AutoSmithy" | "AutoUnits"
  TextLogEntryType: "Error" | "Info"
  Tribe: 6 | 3 | 7 | 5 | 4 | 1 | 2
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AccountSettings: { // root type
    allowTasks: boolean; // Boolean!
    autoAcademy: boolean; // Boolean!
    autoBuild: NexusGenRootTypes['GlobalAutoBuildSettings']; // GlobalAutoBuildSettings!
    autoParty: boolean; // Boolean!
    autoSmithy: boolean; // Boolean!
    autoUnits: boolean; // Boolean!
    tasksCoolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
  }
  AutoAcademySettings: AutoAcademySettings;
  AutoAdventureSettings: { // root type
    adventureCriteria: NexusGenEnums['AdventureCriteria']; // AdventureCriteria!
    allow: boolean; // Boolean!
    coolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
    hardMinHealth: number; // Int!
    maxTravelTime: NexusGenRootTypes['Duration']; // Duration!
    normalMinHealth: number; // Int!
    preferHard: boolean; // Boolean!
  }
  AutoBuildLogEntryContent: { // root type
    fieldId: number; // Int!
    level: number; // Int!
    name: string; // String!
    type: number; // Int!
  }
  AutoBuildSettings: { // root type
    allow: boolean; // Boolean!
    autoCropFields: boolean; // Boolean!
    autoStorage: NexusGenRootTypes['AutoStorageSettings']; // AutoStorageSettings!
    coolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
    dualQueue: NexusGenRootTypes['DualQueueSettings']; // DualQueueSettings!
    minCrop: number; // Int!
    useHeroResources: boolean; // Boolean!
  }
  AutoMentorSettings: { // root type
    acceptDailyRewards: boolean; // Boolean!
    acceptTaskRewards: boolean; // Boolean!
  }
  AutoPartySettings: { // root type
    allowLarge: boolean; // Boolean!
    allowSmall: boolean; // Boolean!
    coolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
    minCulturePointsLarge: number; // Int!
    minCulturePointsSmall: number; // Int!
    useHeroResources: boolean; // Boolean!
  }
  AutoSmithySettings: AutoSmithySettings;
  AutoSmithyUnitLevelSettings: { // root type
    minTroops: number; // Int!
    targetLevel: number; // Int!
  }
  AutoSmithyUnitSettings: AutoSmithyUnitSettings;
  AutoStorageOptionSettings: { // root type
    allow: boolean; // Boolean!
    overflowLevel: number; // Int!
  }
  AutoStorageSettings: { // root type
    allowFreeSpots: boolean; // Boolean!
    granary: NexusGenRootTypes['AutoStorageOptionSettings']; // AutoStorageOptionSettings!
    warehouse: NexusGenRootTypes['AutoStorageOptionSettings']; // AutoStorageOptionSettings!
  }
  AutoUnitsBuildingSettings: { // root type
    allow: boolean; // Boolean!
    maxBuildTime: NexusGenRootTypes['Duration']; // Duration!
    units: NexusGenRootTypes['AutoUnitsUnitSettings'][]; // [AutoUnitsUnitSettings!]!
  }
  AutoUnitsLogEntryContent: { // root type
    amount: number; // Int!
    index: number; // Int!
    tribe: NexusGenEnums['Tribe']; // Tribe!
    unitName: string; // String!
  }
  AutoUnitsSettings: { // root type
    allow: boolean; // Boolean!
    barracks: NexusGenRootTypes['AutoUnitsBuildingSettings']; // AutoUnitsBuildingSettings!
    coolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
    minCrop: number; // Int!
    residence: NexusGenRootTypes['AutoUnitsBuildingSettings']; // AutoUnitsBuildingSettings!
    stable: NexusGenRootTypes['AutoUnitsBuildingSettings']; // AutoUnitsBuildingSettings!
    useHeroResources: boolean; // Boolean!
    workshop: NexusGenRootTypes['AutoUnitsBuildingSettings']; // AutoUnitsBuildingSettings!
  }
  AutoUnitsUnitSettings: { // root type
    autoBuild: boolean; // Boolean!
    index: number; // Int!
    targetAmount: number; // Int!
    trainForever: boolean; // Boolean!
  }
  AvailableNewBuilding: { // root type
    type: number; // Int!
  }
  BuildingInProgress: BuildingInProgress;
  BuildingQueue: BuildingQueue;
  BuildingSpot: BuildingSpot;
  BuildingSpotLevel: { // root type
    actual: number; // Int!
    ongoing?: number | null; // Int
    queued?: number | null; // Int
    state: NexusGenEnums['BuildingState']; // BuildingState!
    total: number; // Int!
  }
  CoolDown: { // root type
    max: NexusGenRootTypes['Duration']; // Duration!
    min: NexusGenRootTypes['Duration']; // Duration!
  }
  Coords: { // root type
    x: number; // Int!
    y: number; // Int!
  }
  DualQueueSettings: { // root type
    allow: boolean; // Boolean!
    preference: NexusGenEnums['DualQueuePreference']; // DualQueuePreference!
  }
  Duration: { // root type
    days: number; // Int!
    hours: number; // Int!
    minutes: number; // Int!
    seconds: number; // Int!
  }
  EnqueueBuildingPayload: { // root type
    addedNew: boolean; // Boolean!
    building: NexusGenRootTypes['QueuedBuilding']; // QueuedBuilding!
    newIndex?: number | null; // Int
    queue: NexusGenRootTypes['BuildingQueue']; // BuildingQueue!
  }
  GameInfo: { // root type
    tribe: NexusGenEnums['Tribe']; // Tribe!
  }
  GeneralSettings: { // root type
    autoStart: boolean; // Boolean!
    chromePath: string; // String!
    headlessChrome: boolean; // Boolean!
  }
  GeneralVillageSettings: GeneralVillageSettings;
  GlobalAutoBuildSettings: { // root type
    allow: boolean; // Boolean!
    videoFeature: NexusGenRootTypes['VideoFeatureSettings']; // VideoFeatureSettings!
  }
  HeroInformation: Hero;
  HeroLevelUpItem: { // root type
    defBonus: number; // Int!
    id: string; // ID!
    name: string; // String!
    offBonus: number; // Int!
    offensiveStrength: number; // Int!
    resources: number; // Int!
  }
  HeroLevelUpSettings: { // root type
    levelUpItems: NexusGenRootTypes['HeroLevelUpItem'][]; // [HeroLevelUpItem!]!
  }
  LogEntry: { // root type
    content: NexusGenRootTypes['LogEntryContent']; // LogEntryContent!
    id: string; // ID!
    timestamp: NexusGenRootTypes['Timestamp']; // Timestamp!
    village?: NexusGenRootTypes['Village'] | null; // Village
  }
  MergeQueueBuildingsPayload: { // root type
    removedBuilding?: NexusGenRootTypes['QueuedBuilding'] | null; // QueuedBuilding
    updatedBuilding?: NexusGenRootTypes['QueuedBuilding'] | null; // QueuedBuilding
  }
  ModificationPayload: { // root type
    queue: NexusGenRootTypes['BuildingQueue']; // BuildingQueue!
    removedBuildings: NexusGenRootTypes['QueuedBuilding'][]; // [QueuedBuilding!]!
    updatedBuildings: NexusGenRootTypes['QueuedBuilding'][]; // [QueuedBuilding!]!
  }
  Mutation: {};
  NextVillageTaskExecutionPayloadField: { // root type
    label: string; // String!
    task: NexusGenEnums['TaskType']; // TaskType!
    timestamp: NexusGenRootTypes['Timestamp']; // Timestamp!
  }
  Query: {};
  QueuedBuilding: QueuedBuilding;
  ResourceClaimLogEntryContent: { // root type
    reason: NexusGenEnums['ClaimHeroResourcesReason']; // ClaimHeroResourcesReason!
    resources: NexusGenRootTypes['Resources']; // Resources!
  }
  ResourceFields: { // root type
    clay: NexusGenRootTypes['BuildingSpot'][]; // [BuildingSpot!]!
    crop: NexusGenRootTypes['BuildingSpot'][]; // [BuildingSpot!]!
    iron: NexusGenRootTypes['BuildingSpot'][]; // [BuildingSpot!]!
    wood: NexusGenRootTypes['BuildingSpot'][]; // [BuildingSpot!]!
  }
  Resources: Resources;
  SplitQueueBuildingPayload: { // root type
    addedBuilding?: NexusGenRootTypes['QueuedBuilding'] | null; // QueuedBuilding
    updatedBuilding?: NexusGenRootTypes['QueuedBuilding'] | null; // QueuedBuilding
  }
  Subscription: {};
  TextLogEntryContent: TextLogEntryContent;
  Timestamp: { // root type
    totalSeconds: number; // Int!
  }
  UnitInfo: { // root type
    name: string; // String!
  }
  UnitUpgradeLogEntryContent: { // root type
    level: number; // Int!
    unitIndex: number; // Int!
  }
  UserAccount: { // root type
    id: string; // ID!
    password: string; // String!
    server: string; // String!
    username: string; // String!
  }
  VideoFeatureSettings: { // root type
    allow: boolean; // Boolean!
    minBuildTime: NexusGenRootTypes['Duration']; // Duration!
  }
  Village: { // root type
    coords: NexusGenRootTypes['Coords']; // Coords!
    id: string; // ID!
    isCapital: boolean; // Boolean!
    name: string; // String!
    resources: NexusGenRootTypes['VillageResources']; // VillageResources!
    scanned: boolean; // Boolean!
  }
  VillageCapacity: { // root type
    granary: number; // Int!
    warehouse: number; // Int!
  }
  VillageCrannyCapacity: { // root type
    actual: number; // Int!
    ongoing: number; // Int!
    total: number; // Int!
  }
  VillageResources: { // root type
    amount: NexusGenRootTypes['Resources']; // Resources!
    capacity: NexusGenRootTypes['VillageCapacity']; // VillageCapacity!
    production: NexusGenRootTypes['Resources']; // Resources!
  }
  VillageTile: { // root type
    claimed?: boolean | null; // Boolean
    coords: NexusGenRootTypes['Coords']; // Coords!
    cropBonus: number; // Int!
    distance: number; // Float!
    type: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
  LogEntryContent: NexusGenRootTypes['AutoBuildLogEntryContent'] | NexusGenRootTypes['AutoUnitsLogEntryContent'] | NexusGenRootTypes['ResourceClaimLogEntryContent'] | NexusGenRootTypes['TextLogEntryContent'] | NexusGenRootTypes['UnitUpgradeLogEntryContent'];
}

export type NexusGenRootTypes = NexusGenObjects & NexusGenUnions

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AccountSettings: { // field return type
    allowTasks: boolean; // Boolean!
    autoAcademy: boolean; // Boolean!
    autoBuild: NexusGenRootTypes['GlobalAutoBuildSettings']; // GlobalAutoBuildSettings!
    autoParty: boolean; // Boolean!
    autoSmithy: boolean; // Boolean!
    autoUnits: boolean; // Boolean!
    tasksCoolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
  }
  AutoAcademySettings: { // field return type
    allow: boolean; // Boolean!
    coolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
    totalCost: NexusGenRootTypes['Resources']; // Resources!
    units: number[]; // [Int!]!
    useHeroResources: boolean; // Boolean!
  }
  AutoAdventureSettings: { // field return type
    adventureCriteria: NexusGenEnums['AdventureCriteria']; // AdventureCriteria!
    allow: boolean; // Boolean!
    coolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
    hardMinHealth: number; // Int!
    maxTravelTime: NexusGenRootTypes['Duration']; // Duration!
    normalMinHealth: number; // Int!
    preferHard: boolean; // Boolean!
  }
  AutoBuildLogEntryContent: { // field return type
    fieldId: number; // Int!
    level: number; // Int!
    name: string; // String!
    type: number; // Int!
  }
  AutoBuildSettings: { // field return type
    allow: boolean; // Boolean!
    autoCropFields: boolean; // Boolean!
    autoStorage: NexusGenRootTypes['AutoStorageSettings']; // AutoStorageSettings!
    coolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
    dualQueue: NexusGenRootTypes['DualQueueSettings']; // DualQueueSettings!
    minCrop: number; // Int!
    useHeroResources: boolean; // Boolean!
  }
  AutoMentorSettings: { // field return type
    acceptDailyRewards: boolean; // Boolean!
    acceptTaskRewards: boolean; // Boolean!
  }
  AutoPartySettings: { // field return type
    allowLarge: boolean; // Boolean!
    allowSmall: boolean; // Boolean!
    coolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
    minCulturePointsLarge: number; // Int!
    minCulturePointsSmall: number; // Int!
    useHeroResources: boolean; // Boolean!
  }
  AutoSmithySettings: { // field return type
    allow: boolean; // Boolean!
    coolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
    units: NexusGenRootTypes['AutoSmithyUnitSettings'][]; // [AutoSmithyUnitSettings!]!
    useHeroResources: boolean; // Boolean!
  }
  AutoSmithyUnitLevelSettings: { // field return type
    minTroops: number; // Int!
    targetLevel: number; // Int!
  }
  AutoSmithyUnitSettings: { // field return type
    levels: NexusGenRootTypes['AutoSmithyUnitLevelSettings'][]; // [AutoSmithyUnitLevelSettings!]!
    unitIndex: number; // Int!
  }
  AutoStorageOptionSettings: { // field return type
    allow: boolean; // Boolean!
    overflowLevel: number; // Int!
  }
  AutoStorageSettings: { // field return type
    allowFreeSpots: boolean; // Boolean!
    granary: NexusGenRootTypes['AutoStorageOptionSettings']; // AutoStorageOptionSettings!
    warehouse: NexusGenRootTypes['AutoStorageOptionSettings']; // AutoStorageOptionSettings!
  }
  AutoUnitsBuildingSettings: { // field return type
    allow: boolean; // Boolean!
    maxBuildTime: NexusGenRootTypes['Duration']; // Duration!
    units: NexusGenRootTypes['AutoUnitsUnitSettings'][]; // [AutoUnitsUnitSettings!]!
  }
  AutoUnitsLogEntryContent: { // field return type
    amount: number; // Int!
    index: number; // Int!
    tribe: NexusGenEnums['Tribe']; // Tribe!
    unitName: string; // String!
  }
  AutoUnitsSettings: { // field return type
    allow: boolean; // Boolean!
    barracks: NexusGenRootTypes['AutoUnitsBuildingSettings']; // AutoUnitsBuildingSettings!
    coolDown: NexusGenRootTypes['CoolDown']; // CoolDown!
    minCrop: number; // Int!
    residence: NexusGenRootTypes['AutoUnitsBuildingSettings']; // AutoUnitsBuildingSettings!
    stable: NexusGenRootTypes['AutoUnitsBuildingSettings']; // AutoUnitsBuildingSettings!
    useHeroResources: boolean; // Boolean!
    workshop: NexusGenRootTypes['AutoUnitsBuildingSettings']; // AutoUnitsBuildingSettings!
  }
  AutoUnitsUnitSettings: { // field return type
    autoBuild: boolean; // Boolean!
    index: number; // Int!
    targetAmount: number; // Int!
    trainForever: boolean; // Boolean!
  }
  AvailableNewBuilding: { // field return type
    maxLevel: number; // Int!
    name: string; // String!
    type: number; // Int!
  }
  BuildingInProgress: { // field return type
    fieldId: number; // Int!
    finishedAt: NexusGenRootTypes['Timestamp']; // Timestamp!
    level: number; // Int!
    name: string; // String!
    type: number; // Int!
  }
  BuildingQueue: { // field return type
    buildings: NexusGenRootTypes['QueuedBuilding'][]; // [QueuedBuilding!]!
    infrastructureBuildingTime: NexusGenRootTypes['Duration']; // Duration!
    resourcesBuildingTime: NexusGenRootTypes['Duration']; // Duration!
    totalBuildingTime: NexusGenRootTypes['Duration']; // Duration!
    totalCost: NexusGenRootTypes['Resources']; // Resources!
  }
  BuildingSpot: { // field return type
    fieldId: number; // Int!
    id: string; // ID!
    level: NexusGenRootTypes['BuildingSpotLevel']; // BuildingSpotLevel!
    maxLevel: number; // Int!
    name: string; // String!
    type: number; // Int!
  }
  BuildingSpotLevel: { // field return type
    actual: number; // Int!
    ongoing: number | null; // Int
    queued: number | null; // Int
    state: NexusGenEnums['BuildingState']; // BuildingState!
    total: number; // Int!
  }
  CoolDown: { // field return type
    max: NexusGenRootTypes['Duration']; // Duration!
    min: NexusGenRootTypes['Duration']; // Duration!
  }
  Coords: { // field return type
    x: number; // Int!
    y: number; // Int!
  }
  DualQueueSettings: { // field return type
    allow: boolean; // Boolean!
    preference: NexusGenEnums['DualQueuePreference']; // DualQueuePreference!
  }
  Duration: { // field return type
    days: number; // Int!
    hours: number; // Int!
    minutes: number; // Int!
    seconds: number; // Int!
  }
  EnqueueBuildingPayload: { // field return type
    addedNew: boolean; // Boolean!
    building: NexusGenRootTypes['QueuedBuilding']; // QueuedBuilding!
    newIndex: number | null; // Int
    queue: NexusGenRootTypes['BuildingQueue']; // BuildingQueue!
  }
  GameInfo: { // field return type
    tribe: NexusGenEnums['Tribe']; // Tribe!
  }
  GeneralSettings: { // field return type
    autoStart: boolean; // Boolean!
    chromePath: string; // String!
    headlessChrome: boolean; // Boolean!
  }
  GeneralVillageSettings: { // field return type
    allowTasks: boolean; // Boolean!
    tasksOrder: NexusGenEnums['TaskType'][]; // [TaskType!]!
  }
  GlobalAutoBuildSettings: { // field return type
    allow: boolean; // Boolean!
    videoFeature: NexusGenRootTypes['VideoFeatureSettings']; // VideoFeatureSettings!
  }
  HeroInformation: { // field return type
    health: number; // Int!
    resources: NexusGenRootTypes['Resources']; // Resources!
    state: NexusGenEnums['HeroState']; // HeroState!
    village: NexusGenRootTypes['Village'] | null; // Village
  }
  HeroLevelUpItem: { // field return type
    defBonus: number; // Int!
    id: string; // ID!
    name: string; // String!
    offBonus: number; // Int!
    offensiveStrength: number; // Int!
    resources: number; // Int!
  }
  HeroLevelUpSettings: { // field return type
    levelUpItems: NexusGenRootTypes['HeroLevelUpItem'][]; // [HeroLevelUpItem!]!
  }
  LogEntry: { // field return type
    content: NexusGenRootTypes['LogEntryContent']; // LogEntryContent!
    id: string; // ID!
    timestamp: NexusGenRootTypes['Timestamp']; // Timestamp!
    village: NexusGenRootTypes['Village'] | null; // Village
  }
  MergeQueueBuildingsPayload: { // field return type
    removedBuilding: NexusGenRootTypes['QueuedBuilding'] | null; // QueuedBuilding
    updatedBuilding: NexusGenRootTypes['QueuedBuilding'] | null; // QueuedBuilding
  }
  ModificationPayload: { // field return type
    queue: NexusGenRootTypes['BuildingQueue']; // BuildingQueue!
    removedBuildings: NexusGenRootTypes['QueuedBuilding'][]; // [QueuedBuilding!]!
    updatedBuildings: NexusGenRootTypes['QueuedBuilding'][]; // [QueuedBuilding!]!
  }
  Mutation: { // field return type
    addAutoSmithyUnitLevel: NexusGenRootTypes['AutoSmithySettings']; // AutoSmithySettings!
    addHeroLevelUpItem: NexusGenRootTypes['HeroLevelUpItem']; // HeroLevelUpItem!
    clearAutoSmithySettingsUnit: NexusGenRootTypes['AutoSmithySettings']; // AutoSmithySettings!
    clearQueue: NexusGenRootTypes['BuildingQueue']; // BuildingQueue!
    createAccount: NexusGenRootTypes['UserAccount']; // UserAccount!
    deleteAccount: NexusGenRootTypes['UserAccount']; // UserAccount!
    dequeueBuilding: NexusGenRootTypes['ModificationPayload']; // ModificationPayload!
    dequeueBuildingAtField: NexusGenRootTypes['ModificationPayload']; // ModificationPayload!
    enqueueBuilding: NexusGenRootTypes['EnqueueBuildingPayload'] | null; // EnqueueBuildingPayload
    exportAccountSettings: boolean | null; // Boolean
    exportAccounts: boolean | null; // Boolean
    exportGeneralSettings: boolean | null; // Boolean
    importAccountSettings: boolean | null; // Boolean
    importAccounts: boolean | null; // Boolean
    importGeneralSettings: boolean | null; // Boolean
    mergeQueuedBuildings: NexusGenRootTypes['MergeQueueBuildingsPayload']; // MergeQueueBuildingsPayload!
    moveQueuedBuildingAsHighAsPossible: NexusGenRootTypes['ModificationPayload']; // ModificationPayload!
    moveQueuedBuildingToIndex: NexusGenRootTypes['ModificationPayload']; // ModificationPayload!
    refreshVillage: boolean | null; // Boolean
    removeAutoSmithyUnitLevel: NexusGenRootTypes['AutoSmithySettings']; // AutoSmithySettings!
    removeHeroLevelUpItem: NexusGenRootTypes['HeroLevelUpItem']; // HeroLevelUpItem!
    resetAccountSettings: NexusGenRootTypes['AccountSettings']; // AccountSettings!
    resetAutoAcademySettings: NexusGenRootTypes['AutoAcademySettings']; // AutoAcademySettings!
    resetAutoAdventureSettings: NexusGenRootTypes['AutoAdventureSettings']; // AutoAdventureSettings!
    resetAutoBuildSettings: NexusGenRootTypes['AutoBuildSettings']; // AutoBuildSettings!
    resetAutoMentorSettings: NexusGenRootTypes['AutoMentorSettings']; // AutoMentorSettings!
    resetAutoPartySettings: NexusGenRootTypes['AutoPartySettings']; // AutoPartySettings!
    resetAutoSmithySettings: NexusGenRootTypes['AutoSmithySettings']; // AutoSmithySettings!
    resetAutoSmithySettingsUnits: NexusGenRootTypes['AutoSmithySettings']; // AutoSmithySettings!
    resetAutoUnitsSettings: NexusGenRootTypes['AutoUnitsSettings']; // AutoUnitsSettings!
    resetGeneralSettings: NexusGenRootTypes['GeneralSettings']; // GeneralSettings!
    resetGeneralVillageSettings: NexusGenRootTypes['GeneralVillageSettings']; // GeneralVillageSettings!
    resetNextTaskExecution: NexusGenRootTypes['Timestamp']; // Timestamp!
    resetNextTasksExecution: NexusGenRootTypes['Timestamp']; // Timestamp!
    resetNextVillageTaskExecution: NexusGenRootTypes['Timestamp']; // Timestamp!
    scanWholeMap: boolean | null; // Boolean
    searchMap: boolean | null; // Boolean
    setAutoAcademySettingsUnits: NexusGenRootTypes['AutoAcademySettings']; // AutoAcademySettings!
    setNextTaskExecution: NexusGenRootTypes['Timestamp']; // Timestamp!
    setNextTasksExecution: NexusGenRootTypes['Timestamp']; // Timestamp!
    setNextVillageTaskExecution: NexusGenRootTypes['Timestamp']; // Timestamp!
    signIn: boolean | null; // Boolean
    signOut: boolean | null; // Boolean
    splitQueuedBuilding: NexusGenRootTypes['SplitQueueBuildingPayload']; // SplitQueueBuildingPayload!
    startBot: boolean | null; // Boolean
    stopBot: boolean | null; // Boolean
    stopMapScan: boolean | null; // Boolean
    updateAccount: NexusGenRootTypes['UserAccount']; // UserAccount!
    updateAccountSettings: NexusGenRootTypes['AccountSettings']; // AccountSettings!
    updateAutoAcademySettings: NexusGenRootTypes['AutoAcademySettings']; // AutoAcademySettings!
    updateAutoAdventureSettings: NexusGenRootTypes['AutoAdventureSettings']; // AutoAdventureSettings!
    updateAutoBuildSettings: NexusGenRootTypes['AutoBuildSettings']; // AutoBuildSettings!
    updateAutoMentorSettings: NexusGenRootTypes['AutoMentorSettings']; // AutoMentorSettings!
    updateAutoPartySettings: NexusGenRootTypes['AutoPartySettings']; // AutoPartySettings!
    updateAutoSmithySettings: NexusGenRootTypes['AutoSmithySettings']; // AutoSmithySettings!
    updateAutoUnitsBuildingSettings: NexusGenRootTypes['AutoUnitsSettings']; // AutoUnitsSettings!
    updateAutoUnitsSettings: NexusGenRootTypes['AutoUnitsSettings']; // AutoUnitsSettings!
    updateAutoUnitsUnitSettings: NexusGenRootTypes['AutoUnitsSettings']; // AutoUnitsSettings!
    updateGeneralSettings: NexusGenRootTypes['GeneralSettings']; // GeneralSettings!
    updateGeneralVillageSettings: NexusGenRootTypes['GeneralVillageSettings']; // GeneralVillageSettings!
    updateGeneralVillageSettingsOrder: NexusGenRootTypes['GeneralVillageSettings']; // GeneralVillageSettings!
    updateHeroLevelUpItem: NexusGenRootTypes['HeroLevelUpItem']; // HeroLevelUpItem!
  }
  NextVillageTaskExecutionPayloadField: { // field return type
    label: string; // String!
    task: NexusGenEnums['TaskType']; // TaskType!
    timestamp: NexusGenRootTypes['Timestamp']; // Timestamp!
  }
  Query: { // field return type
    account: NexusGenRootTypes['UserAccount']; // UserAccount!
    accountSettings: NexusGenRootTypes['AccountSettings']; // AccountSettings!
    accounts: NexusGenRootTypes['UserAccount'][]; // [UserAccount!]!
    activeVillageId: string; // ID!
    autoAcademySettings: NexusGenRootTypes['AutoAcademySettings']; // AutoAcademySettings!
    autoAdventureSettings: NexusGenRootTypes['AutoAdventureSettings']; // AutoAdventureSettings!
    autoBuildSettings: NexusGenRootTypes['AutoBuildSettings']; // AutoBuildSettings!
    autoMentorSettings: NexusGenRootTypes['AutoMentorSettings']; // AutoMentorSettings!
    autoPartySettings: NexusGenRootTypes['AutoPartySettings']; // AutoPartySettings!
    autoSmithySettings: NexusGenRootTypes['AutoSmithySettings']; // AutoSmithySettings!
    autoUnitsSettings: NexusGenRootTypes['AutoUnitsSettings']; // AutoUnitsSettings!
    availableNewBuildings: NexusGenRootTypes['AvailableNewBuilding'][]; // [AvailableNewBuilding!]!
    botActivity: string; // String!
    botState: NexusGenEnums['BotState']; // BotState!
    buildingQueue: NexusGenRootTypes['BuildingQueue']; // BuildingQueue!
    buildingsInProgress: NexusGenRootTypes['BuildingInProgress'][]; // [BuildingInProgress!]!
    canMoveQueuedBuilding: boolean; // Boolean!
    crannyCapacity: NexusGenRootTypes['VillageCrannyCapacity']; // VillageCrannyCapacity!
    currentAccount: NexusGenRootTypes['UserAccount']; // UserAccount!
    gameInfo: NexusGenRootTypes['GameInfo']; // GameInfo!
    generalSettings: NexusGenRootTypes['GeneralSettings']; // GeneralSettings!
    generalVillageSettings: NexusGenRootTypes['GeneralVillageSettings']; // GeneralVillageSettings!
    heroInformation: NexusGenRootTypes['HeroInformation']; // HeroInformation!
    heroLevelUpSettings: NexusGenRootTypes['HeroLevelUpSettings']; // HeroLevelUpSettings!
    infrastructure: NexusGenRootTypes['BuildingSpot'][]; // [BuildingSpot!]!
    isAccountTaken: boolean; // Boolean!
    lastSignedAccountId: string | null; // String
    logEntries: NexusGenRootTypes['LogEntry'][]; // [LogEntry!]!
    mapScanProgress: number; // Float!
    mapSearchState: NexusGenEnums['MapSearchState']; // MapSearchState!
    nextTaskExecution: NexusGenRootTypes['Timestamp']; // Timestamp!
    nextTasksExecution: NexusGenRootTypes['Timestamp']; // Timestamp!
    nextVillageTaskExecution: NexusGenRootTypes['Timestamp']; // Timestamp!
    nextVillageTaskExecutions: NexusGenRootTypes['NextVillageTaskExecutionPayloadField'][]; // [NextVillageTaskExecutionPayloadField!]!
    researcheableUnits: number[]; // [Int!]!
    resourceFields: NexusGenRootTypes['BuildingSpot'][]; // [BuildingSpot!]!
    unitInfo: NexusGenRootTypes['UnitInfo']; // UnitInfo!
    unitUpgradeCost: NexusGenRootTypes['Resources']; // Resources!
    upgradeableUnits: number[]; // [Int!]!
    village: NexusGenRootTypes['Village'] | null; // Village
    villageTileTypes: string[]; // [String!]!
    villages: NexusGenRootTypes['Village'][]; // [Village!]!
  }
  QueuedBuilding: { // field return type
    buildingTime: NexusGenRootTypes['Duration']; // Duration!
    cost: NexusGenRootTypes['Resources']; // Resources!
    fieldId: number; // Int!
    id: string; // ID!
    name: string; // String!
    startingLevel: number; // Int!
    targetLevel: number; // Int!
    type: number; // Int!
  }
  ResourceClaimLogEntryContent: { // field return type
    reason: NexusGenEnums['ClaimHeroResourcesReason']; // ClaimHeroResourcesReason!
    resources: NexusGenRootTypes['Resources']; // Resources!
  }
  ResourceFields: { // field return type
    clay: NexusGenRootTypes['BuildingSpot'][]; // [BuildingSpot!]!
    crop: NexusGenRootTypes['BuildingSpot'][]; // [BuildingSpot!]!
    iron: NexusGenRootTypes['BuildingSpot'][]; // [BuildingSpot!]!
    wood: NexusGenRootTypes['BuildingSpot'][]; // [BuildingSpot!]!
  }
  Resources: { // field return type
    clay: number; // Int!
    crop: number; // Int!
    freeCrop: number; // Int!
    iron: number; // Int!
    total: number; // Int!
    wood: number; // Int!
  }
  SplitQueueBuildingPayload: { // field return type
    addedBuilding: NexusGenRootTypes['QueuedBuilding'] | null; // QueuedBuilding
    updatedBuilding: NexusGenRootTypes['QueuedBuilding'] | null; // QueuedBuilding
  }
  Subscription: { // field return type
    accountSettingsUpdated: NexusGenRootTypes['AccountSettings']; // AccountSettings!
    accountsUpdated: NexusGenRootTypes['UserAccount'][]; // [UserAccount!]!
    activeVillageIdChanged: string; // ID!
    autoAcademySettingsUpdated: NexusGenRootTypes['AutoAcademySettings']; // AutoAcademySettings!
    autoAdventureSettingsUpdated: NexusGenRootTypes['AutoAdventureSettings']; // AutoAdventureSettings!
    autoBuildSettingsUpdated: NexusGenRootTypes['AutoBuildSettings']; // AutoBuildSettings!
    autoMentorSettingsUpdated: NexusGenRootTypes['AutoMentorSettings']; // AutoMentorSettings!
    autoSmithySettingsUnitRemoved: NexusGenRootTypes['AutoSmithyUnitSettings']; // AutoSmithyUnitSettings!
    autoSmithySettingsUnitUpdated: NexusGenRootTypes['AutoSmithyUnitSettings']; // AutoSmithyUnitSettings!
    autoSmithySettingsUpdated: NexusGenRootTypes['AutoSmithySettings']; // AutoSmithySettings!
    autoUnitsSettingsUpdated: NexusGenRootTypes['AutoUnitsSettings']; // AutoUnitsSettings!
    botActivityChanged: string; // String!
    botStateChanged: NexusGenEnums['BotState']; // BotState!
    buildingQueueCorrected: NexusGenRootTypes['ModificationPayload']; // ModificationPayload!
    buildingQueueTimesUpdated: NexusGenRootTypes['BuildingQueue']; // BuildingQueue!
    buildingsInProgressUpdated: NexusGenRootTypes['BuildingInProgress'][]; // [BuildingInProgress!]!
    generalVillageSettingsUpdated: NexusGenRootTypes['GeneralVillageSettings']; // GeneralVillageSettings!
    heroInformationUpdated: NexusGenRootTypes['HeroInformation']; // HeroInformation!
    heroLevelUpSettingsChanged: NexusGenRootTypes['HeroLevelUpSettings']; // HeroLevelUpSettings!
    lastSignedAccountIdUpdated: string | null; // String
    logEntryAdded: NexusGenRootTypes['LogEntry']; // LogEntry!
    mapScanProgressUpdated: number; // Float!
    mapSearchFinished: NexusGenRootTypes['VillageTile'][]; // [VillageTile!]!
    mapSearchStateChanged: NexusGenEnums['MapSearchState']; // MapSearchState!
    nextTaskExecutionChanged: NexusGenRootTypes['Timestamp']; // Timestamp!
    nextTasksExecutionChanged: NexusGenRootTypes['Timestamp']; // Timestamp!
    nextVillageTaskExecutionChanged: NexusGenRootTypes['Timestamp']; // Timestamp!
    onBuildingSpotUpdated: NexusGenRootTypes['BuildingSpot']; // BuildingSpot!
    onCrannyCapacityUpdated: NexusGenRootTypes['VillageCrannyCapacity']; // VillageCrannyCapacity!
    onGameInfoUpdated: NexusGenRootTypes['GameInfo']; // GameInfo!
    queuedBuildingUpdated: NexusGenRootTypes['ModificationPayload']; // ModificationPayload!
    villageUpdated: NexusGenRootTypes['Village']; // Village!
    villagesUpdated: NexusGenRootTypes['Village'][]; // [Village!]!
  }
  TextLogEntryContent: { // field return type
    message: string; // String!
    messageType: NexusGenEnums['TextLogEntryType']; // TextLogEntryType!
  }
  Timestamp: { // field return type
    totalSeconds: number; // Int!
  }
  UnitInfo: { // field return type
    name: string; // String!
  }
  UnitUpgradeLogEntryContent: { // field return type
    level: number; // Int!
    unitIndex: number; // Int!
  }
  UserAccount: { // field return type
    id: string; // ID!
    password: string; // String!
    server: string; // String!
    username: string; // String!
  }
  VideoFeatureSettings: { // field return type
    allow: boolean; // Boolean!
    minBuildTime: NexusGenRootTypes['Duration']; // Duration!
  }
  Village: { // field return type
    coords: NexusGenRootTypes['Coords']; // Coords!
    id: string; // ID!
    isCapital: boolean; // Boolean!
    name: string; // String!
    resources: NexusGenRootTypes['VillageResources']; // VillageResources!
    scanned: boolean; // Boolean!
  }
  VillageCapacity: { // field return type
    granary: number; // Int!
    warehouse: number; // Int!
  }
  VillageCrannyCapacity: { // field return type
    actual: number; // Int!
    ongoing: number; // Int!
    total: number; // Int!
  }
  VillageResources: { // field return type
    amount: NexusGenRootTypes['Resources']; // Resources!
    capacity: NexusGenRootTypes['VillageCapacity']; // VillageCapacity!
    production: NexusGenRootTypes['Resources']; // Resources!
  }
  VillageTile: { // field return type
    claimed: boolean | null; // Boolean
    coords: NexusGenRootTypes['Coords']; // Coords!
    cropBonus: number; // Int!
    distance: number; // Float!
    type: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AccountSettings: { // field return type name
    allowTasks: 'Boolean'
    autoAcademy: 'Boolean'
    autoBuild: 'GlobalAutoBuildSettings'
    autoParty: 'Boolean'
    autoSmithy: 'Boolean'
    autoUnits: 'Boolean'
    tasksCoolDown: 'CoolDown'
  }
  AutoAcademySettings: { // field return type name
    allow: 'Boolean'
    coolDown: 'CoolDown'
    totalCost: 'Resources'
    units: 'Int'
    useHeroResources: 'Boolean'
  }
  AutoAdventureSettings: { // field return type name
    adventureCriteria: 'AdventureCriteria'
    allow: 'Boolean'
    coolDown: 'CoolDown'
    hardMinHealth: 'Int'
    maxTravelTime: 'Duration'
    normalMinHealth: 'Int'
    preferHard: 'Boolean'
  }
  AutoBuildLogEntryContent: { // field return type name
    fieldId: 'Int'
    level: 'Int'
    name: 'String'
    type: 'Int'
  }
  AutoBuildSettings: { // field return type name
    allow: 'Boolean'
    autoCropFields: 'Boolean'
    autoStorage: 'AutoStorageSettings'
    coolDown: 'CoolDown'
    dualQueue: 'DualQueueSettings'
    minCrop: 'Int'
    useHeroResources: 'Boolean'
  }
  AutoMentorSettings: { // field return type name
    acceptDailyRewards: 'Boolean'
    acceptTaskRewards: 'Boolean'
  }
  AutoPartySettings: { // field return type name
    allowLarge: 'Boolean'
    allowSmall: 'Boolean'
    coolDown: 'CoolDown'
    minCulturePointsLarge: 'Int'
    minCulturePointsSmall: 'Int'
    useHeroResources: 'Boolean'
  }
  AutoSmithySettings: { // field return type name
    allow: 'Boolean'
    coolDown: 'CoolDown'
    units: 'AutoSmithyUnitSettings'
    useHeroResources: 'Boolean'
  }
  AutoSmithyUnitLevelSettings: { // field return type name
    minTroops: 'Int'
    targetLevel: 'Int'
  }
  AutoSmithyUnitSettings: { // field return type name
    levels: 'AutoSmithyUnitLevelSettings'
    unitIndex: 'Int'
  }
  AutoStorageOptionSettings: { // field return type name
    allow: 'Boolean'
    overflowLevel: 'Int'
  }
  AutoStorageSettings: { // field return type name
    allowFreeSpots: 'Boolean'
    granary: 'AutoStorageOptionSettings'
    warehouse: 'AutoStorageOptionSettings'
  }
  AutoUnitsBuildingSettings: { // field return type name
    allow: 'Boolean'
    maxBuildTime: 'Duration'
    units: 'AutoUnitsUnitSettings'
  }
  AutoUnitsLogEntryContent: { // field return type name
    amount: 'Int'
    index: 'Int'
    tribe: 'Tribe'
    unitName: 'String'
  }
  AutoUnitsSettings: { // field return type name
    allow: 'Boolean'
    barracks: 'AutoUnitsBuildingSettings'
    coolDown: 'CoolDown'
    minCrop: 'Int'
    residence: 'AutoUnitsBuildingSettings'
    stable: 'AutoUnitsBuildingSettings'
    useHeroResources: 'Boolean'
    workshop: 'AutoUnitsBuildingSettings'
  }
  AutoUnitsUnitSettings: { // field return type name
    autoBuild: 'Boolean'
    index: 'Int'
    targetAmount: 'Int'
    trainForever: 'Boolean'
  }
  AvailableNewBuilding: { // field return type name
    maxLevel: 'Int'
    name: 'String'
    type: 'Int'
  }
  BuildingInProgress: { // field return type name
    fieldId: 'Int'
    finishedAt: 'Timestamp'
    level: 'Int'
    name: 'String'
    type: 'Int'
  }
  BuildingQueue: { // field return type name
    buildings: 'QueuedBuilding'
    infrastructureBuildingTime: 'Duration'
    resourcesBuildingTime: 'Duration'
    totalBuildingTime: 'Duration'
    totalCost: 'Resources'
  }
  BuildingSpot: { // field return type name
    fieldId: 'Int'
    id: 'ID'
    level: 'BuildingSpotLevel'
    maxLevel: 'Int'
    name: 'String'
    type: 'Int'
  }
  BuildingSpotLevel: { // field return type name
    actual: 'Int'
    ongoing: 'Int'
    queued: 'Int'
    state: 'BuildingState'
    total: 'Int'
  }
  CoolDown: { // field return type name
    max: 'Duration'
    min: 'Duration'
  }
  Coords: { // field return type name
    x: 'Int'
    y: 'Int'
  }
  DualQueueSettings: { // field return type name
    allow: 'Boolean'
    preference: 'DualQueuePreference'
  }
  Duration: { // field return type name
    days: 'Int'
    hours: 'Int'
    minutes: 'Int'
    seconds: 'Int'
  }
  EnqueueBuildingPayload: { // field return type name
    addedNew: 'Boolean'
    building: 'QueuedBuilding'
    newIndex: 'Int'
    queue: 'BuildingQueue'
  }
  GameInfo: { // field return type name
    tribe: 'Tribe'
  }
  GeneralSettings: { // field return type name
    autoStart: 'Boolean'
    chromePath: 'String'
    headlessChrome: 'Boolean'
  }
  GeneralVillageSettings: { // field return type name
    allowTasks: 'Boolean'
    tasksOrder: 'TaskType'
  }
  GlobalAutoBuildSettings: { // field return type name
    allow: 'Boolean'
    videoFeature: 'VideoFeatureSettings'
  }
  HeroInformation: { // field return type name
    health: 'Int'
    resources: 'Resources'
    state: 'HeroState'
    village: 'Village'
  }
  HeroLevelUpItem: { // field return type name
    defBonus: 'Int'
    id: 'ID'
    name: 'String'
    offBonus: 'Int'
    offensiveStrength: 'Int'
    resources: 'Int'
  }
  HeroLevelUpSettings: { // field return type name
    levelUpItems: 'HeroLevelUpItem'
  }
  LogEntry: { // field return type name
    content: 'LogEntryContent'
    id: 'ID'
    timestamp: 'Timestamp'
    village: 'Village'
  }
  MergeQueueBuildingsPayload: { // field return type name
    removedBuilding: 'QueuedBuilding'
    updatedBuilding: 'QueuedBuilding'
  }
  ModificationPayload: { // field return type name
    queue: 'BuildingQueue'
    removedBuildings: 'QueuedBuilding'
    updatedBuildings: 'QueuedBuilding'
  }
  Mutation: { // field return type name
    addAutoSmithyUnitLevel: 'AutoSmithySettings'
    addHeroLevelUpItem: 'HeroLevelUpItem'
    clearAutoSmithySettingsUnit: 'AutoSmithySettings'
    clearQueue: 'BuildingQueue'
    createAccount: 'UserAccount'
    deleteAccount: 'UserAccount'
    dequeueBuilding: 'ModificationPayload'
    dequeueBuildingAtField: 'ModificationPayload'
    enqueueBuilding: 'EnqueueBuildingPayload'
    exportAccountSettings: 'Boolean'
    exportAccounts: 'Boolean'
    exportGeneralSettings: 'Boolean'
    importAccountSettings: 'Boolean'
    importAccounts: 'Boolean'
    importGeneralSettings: 'Boolean'
    mergeQueuedBuildings: 'MergeQueueBuildingsPayload'
    moveQueuedBuildingAsHighAsPossible: 'ModificationPayload'
    moveQueuedBuildingToIndex: 'ModificationPayload'
    refreshVillage: 'Boolean'
    removeAutoSmithyUnitLevel: 'AutoSmithySettings'
    removeHeroLevelUpItem: 'HeroLevelUpItem'
    resetAccountSettings: 'AccountSettings'
    resetAutoAcademySettings: 'AutoAcademySettings'
    resetAutoAdventureSettings: 'AutoAdventureSettings'
    resetAutoBuildSettings: 'AutoBuildSettings'
    resetAutoMentorSettings: 'AutoMentorSettings'
    resetAutoPartySettings: 'AutoPartySettings'
    resetAutoSmithySettings: 'AutoSmithySettings'
    resetAutoSmithySettingsUnits: 'AutoSmithySettings'
    resetAutoUnitsSettings: 'AutoUnitsSettings'
    resetGeneralSettings: 'GeneralSettings'
    resetGeneralVillageSettings: 'GeneralVillageSettings'
    resetNextTaskExecution: 'Timestamp'
    resetNextTasksExecution: 'Timestamp'
    resetNextVillageTaskExecution: 'Timestamp'
    scanWholeMap: 'Boolean'
    searchMap: 'Boolean'
    setAutoAcademySettingsUnits: 'AutoAcademySettings'
    setNextTaskExecution: 'Timestamp'
    setNextTasksExecution: 'Timestamp'
    setNextVillageTaskExecution: 'Timestamp'
    signIn: 'Boolean'
    signOut: 'Boolean'
    splitQueuedBuilding: 'SplitQueueBuildingPayload'
    startBot: 'Boolean'
    stopBot: 'Boolean'
    stopMapScan: 'Boolean'
    updateAccount: 'UserAccount'
    updateAccountSettings: 'AccountSettings'
    updateAutoAcademySettings: 'AutoAcademySettings'
    updateAutoAdventureSettings: 'AutoAdventureSettings'
    updateAutoBuildSettings: 'AutoBuildSettings'
    updateAutoMentorSettings: 'AutoMentorSettings'
    updateAutoPartySettings: 'AutoPartySettings'
    updateAutoSmithySettings: 'AutoSmithySettings'
    updateAutoUnitsBuildingSettings: 'AutoUnitsSettings'
    updateAutoUnitsSettings: 'AutoUnitsSettings'
    updateAutoUnitsUnitSettings: 'AutoUnitsSettings'
    updateGeneralSettings: 'GeneralSettings'
    updateGeneralVillageSettings: 'GeneralVillageSettings'
    updateGeneralVillageSettingsOrder: 'GeneralVillageSettings'
    updateHeroLevelUpItem: 'HeroLevelUpItem'
  }
  NextVillageTaskExecutionPayloadField: { // field return type name
    label: 'String'
    task: 'TaskType'
    timestamp: 'Timestamp'
  }
  Query: { // field return type name
    account: 'UserAccount'
    accountSettings: 'AccountSettings'
    accounts: 'UserAccount'
    activeVillageId: 'ID'
    autoAcademySettings: 'AutoAcademySettings'
    autoAdventureSettings: 'AutoAdventureSettings'
    autoBuildSettings: 'AutoBuildSettings'
    autoMentorSettings: 'AutoMentorSettings'
    autoPartySettings: 'AutoPartySettings'
    autoSmithySettings: 'AutoSmithySettings'
    autoUnitsSettings: 'AutoUnitsSettings'
    availableNewBuildings: 'AvailableNewBuilding'
    botActivity: 'String'
    botState: 'BotState'
    buildingQueue: 'BuildingQueue'
    buildingsInProgress: 'BuildingInProgress'
    canMoveQueuedBuilding: 'Boolean'
    crannyCapacity: 'VillageCrannyCapacity'
    currentAccount: 'UserAccount'
    gameInfo: 'GameInfo'
    generalSettings: 'GeneralSettings'
    generalVillageSettings: 'GeneralVillageSettings'
    heroInformation: 'HeroInformation'
    heroLevelUpSettings: 'HeroLevelUpSettings'
    infrastructure: 'BuildingSpot'
    isAccountTaken: 'Boolean'
    lastSignedAccountId: 'String'
    logEntries: 'LogEntry'
    mapScanProgress: 'Float'
    mapSearchState: 'MapSearchState'
    nextTaskExecution: 'Timestamp'
    nextTasksExecution: 'Timestamp'
    nextVillageTaskExecution: 'Timestamp'
    nextVillageTaskExecutions: 'NextVillageTaskExecutionPayloadField'
    researcheableUnits: 'Int'
    resourceFields: 'BuildingSpot'
    unitInfo: 'UnitInfo'
    unitUpgradeCost: 'Resources'
    upgradeableUnits: 'Int'
    village: 'Village'
    villageTileTypes: 'String'
    villages: 'Village'
  }
  QueuedBuilding: { // field return type name
    buildingTime: 'Duration'
    cost: 'Resources'
    fieldId: 'Int'
    id: 'ID'
    name: 'String'
    startingLevel: 'Int'
    targetLevel: 'Int'
    type: 'Int'
  }
  ResourceClaimLogEntryContent: { // field return type name
    reason: 'ClaimHeroResourcesReason'
    resources: 'Resources'
  }
  ResourceFields: { // field return type name
    clay: 'BuildingSpot'
    crop: 'BuildingSpot'
    iron: 'BuildingSpot'
    wood: 'BuildingSpot'
  }
  Resources: { // field return type name
    clay: 'Int'
    crop: 'Int'
    freeCrop: 'Int'
    iron: 'Int'
    total: 'Int'
    wood: 'Int'
  }
  SplitQueueBuildingPayload: { // field return type name
    addedBuilding: 'QueuedBuilding'
    updatedBuilding: 'QueuedBuilding'
  }
  Subscription: { // field return type name
    accountSettingsUpdated: 'AccountSettings'
    accountsUpdated: 'UserAccount'
    activeVillageIdChanged: 'ID'
    autoAcademySettingsUpdated: 'AutoAcademySettings'
    autoAdventureSettingsUpdated: 'AutoAdventureSettings'
    autoBuildSettingsUpdated: 'AutoBuildSettings'
    autoMentorSettingsUpdated: 'AutoMentorSettings'
    autoSmithySettingsUnitRemoved: 'AutoSmithyUnitSettings'
    autoSmithySettingsUnitUpdated: 'AutoSmithyUnitSettings'
    autoSmithySettingsUpdated: 'AutoSmithySettings'
    autoUnitsSettingsUpdated: 'AutoUnitsSettings'
    botActivityChanged: 'String'
    botStateChanged: 'BotState'
    buildingQueueCorrected: 'ModificationPayload'
    buildingQueueTimesUpdated: 'BuildingQueue'
    buildingsInProgressUpdated: 'BuildingInProgress'
    generalVillageSettingsUpdated: 'GeneralVillageSettings'
    heroInformationUpdated: 'HeroInformation'
    heroLevelUpSettingsChanged: 'HeroLevelUpSettings'
    lastSignedAccountIdUpdated: 'String'
    logEntryAdded: 'LogEntry'
    mapScanProgressUpdated: 'Float'
    mapSearchFinished: 'VillageTile'
    mapSearchStateChanged: 'MapSearchState'
    nextTaskExecutionChanged: 'Timestamp'
    nextTasksExecutionChanged: 'Timestamp'
    nextVillageTaskExecutionChanged: 'Timestamp'
    onBuildingSpotUpdated: 'BuildingSpot'
    onCrannyCapacityUpdated: 'VillageCrannyCapacity'
    onGameInfoUpdated: 'GameInfo'
    queuedBuildingUpdated: 'ModificationPayload'
    villageUpdated: 'Village'
    villagesUpdated: 'Village'
  }
  TextLogEntryContent: { // field return type name
    message: 'String'
    messageType: 'TextLogEntryType'
  }
  Timestamp: { // field return type name
    totalSeconds: 'Int'
  }
  UnitInfo: { // field return type name
    name: 'String'
  }
  UnitUpgradeLogEntryContent: { // field return type name
    level: 'Int'
    unitIndex: 'Int'
  }
  UserAccount: { // field return type name
    id: 'ID'
    password: 'String'
    server: 'String'
    username: 'String'
  }
  VideoFeatureSettings: { // field return type name
    allow: 'Boolean'
    minBuildTime: 'Duration'
  }
  Village: { // field return type name
    coords: 'Coords'
    id: 'ID'
    isCapital: 'Boolean'
    name: 'String'
    resources: 'VillageResources'
    scanned: 'Boolean'
  }
  VillageCapacity: { // field return type name
    granary: 'Int'
    warehouse: 'Int'
  }
  VillageCrannyCapacity: { // field return type name
    actual: 'Int'
    ongoing: 'Int'
    total: 'Int'
  }
  VillageResources: { // field return type name
    amount: 'Resources'
    capacity: 'VillageCapacity'
    production: 'Resources'
  }
  VillageTile: { // field return type name
    claimed: 'Boolean'
    coords: 'Coords'
    cropBonus: 'Int'
    distance: 'Float'
    type: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addAutoSmithyUnitLevel: { // args
      minTroops: number; // Int!
      targetLevel: number; // Int!
      unitIndex: number; // Int!
      villageId: string; // ID!
    }
    addHeroLevelUpItem: { // args
      item: NexusGenInputs['HeroLevelUpItemInput']; // HeroLevelUpItemInput!
    }
    clearAutoSmithySettingsUnit: { // args
      unitIndex: number; // Int!
      villageId: string; // ID!
    }
    clearQueue: { // args
      villageId: string; // ID!
    }
    createAccount: { // args
      account: NexusGenInputs['AccountInput']; // AccountInput!
    }
    deleteAccount: { // args
      id: string; // ID!
    }
    dequeueBuilding: { // args
      input: NexusGenInputs['DequeueBuildingInput']; // DequeueBuildingInput!
    }
    dequeueBuildingAtField: { // args
      input: NexusGenInputs['DequeueBuildingAtFieldInput']; // DequeueBuildingAtFieldInput!
    }
    enqueueBuilding: { // args
      input: NexusGenInputs['EnqueueBuildingInput']; // EnqueueBuildingInput!
    }
    exportAccountSettings: { // args
      accountId: string; // ID!
      path: string; // String!
    }
    exportAccounts: { // args
      path: string; // String!
    }
    exportGeneralSettings: { // args
      path: string; // String!
    }
    importAccountSettings: { // args
      accountId: string; // ID!
      path: string; // String!
    }
    importAccounts: { // args
      path: string; // String!
    }
    importGeneralSettings: { // args
      path: string; // String!
    }
    mergeQueuedBuildings: { // args
      topQueueId: string; // ID!
      villageId: string; // ID!
    }
    moveQueuedBuildingAsHighAsPossible: { // args
      queueId: string; // ID!
      villageId: string; // ID!
    }
    moveQueuedBuildingToIndex: { // args
      queueId: string; // ID!
      targetQueueId: string; // ID!
      villageId: string; // ID!
    }
    refreshVillage: { // args
      villageId: string; // ID!
    }
    removeAutoSmithyUnitLevel: { // args
      targetLevel: number; // Int!
      unitIndex: number; // Int!
      villageId: string; // ID!
    }
    removeHeroLevelUpItem: { // args
      id: string; // ID!
    }
    resetAutoAcademySettings: { // args
      villageId: string; // ID!
    }
    resetAutoBuildSettings: { // args
      villageId: string; // ID!
    }
    resetAutoPartySettings: { // args
      villageId: string; // ID!
    }
    resetAutoSmithySettings: { // args
      villageId: string; // ID!
    }
    resetAutoSmithySettingsUnits: { // args
      villageId: string; // ID!
    }
    resetAutoUnitsSettings: { // args
      villageId: string; // ID!
    }
    resetGeneralVillageSettings: { // args
      villageId: string; // ID!
    }
    resetNextTaskExecution: { // args
      task: NexusGenEnums['TaskType']; // TaskType!
    }
    resetNextVillageTaskExecution: { // args
      task: NexusGenEnums['TaskType']; // TaskType!
      villageId: string; // ID!
    }
    searchMap: { // args
      input: NexusGenInputs['SearchMapInput']; // SearchMapInput!
    }
    setAutoAcademySettingsUnits: { // args
      units: number[]; // [Int!]!
      villageId: string; // ID!
    }
    setNextTaskExecution: { // args
      delay: NexusGenInputs['DurationInput']; // DurationInput!
      task: NexusGenEnums['TaskType']; // TaskType!
    }
    setNextTasksExecution: { // args
      delay: NexusGenInputs['DurationInput']; // DurationInput!
    }
    setNextVillageTaskExecution: { // args
      delay: NexusGenInputs['DurationInput']; // DurationInput!
      task: NexusGenEnums['TaskType']; // TaskType!
      villageId: string; // ID!
    }
    signIn: { // args
      accountId: string; // ID!
    }
    splitQueuedBuilding: { // args
      queueId: string; // ID!
      startingLevel: number; // Int!
      villageId: string; // ID!
    }
    updateAccount: { // args
      account: NexusGenInputs['AccountInput']; // AccountInput!
      id: string; // ID!
    }
    updateAccountSettings: { // args
      settings: NexusGenInputs['UpdateAccountSettingsInput']; // UpdateAccountSettingsInput!
    }
    updateAutoAcademySettings: { // args
      settings: NexusGenInputs['AutoAcademySettingsInput']; // AutoAcademySettingsInput!
      villageId: string; // ID!
    }
    updateAutoAdventureSettings: { // args
      settings: NexusGenInputs['UpdateAutoAdventureSettingsInput']; // UpdateAutoAdventureSettingsInput!
    }
    updateAutoBuildSettings: { // args
      settings: NexusGenInputs['UpdateAutoBuildSettingsInput']; // UpdateAutoBuildSettingsInput!
      villageId: string; // ID!
    }
    updateAutoMentorSettings: { // args
      settings: NexusGenInputs['UpdateAutoMentorSettingsInput']; // UpdateAutoMentorSettingsInput!
    }
    updateAutoPartySettings: { // args
      settings: NexusGenInputs['UpdateAutoPartySettingsInput']; // UpdateAutoPartySettingsInput!
      villageId: string; // ID!
    }
    updateAutoSmithySettings: { // args
      settings: NexusGenInputs['AutoSmithySettingsInput']; // AutoSmithySettingsInput!
      villageId: string; // ID!
    }
    updateAutoUnitsBuildingSettings: { // args
      buildingType: number; // Int!
      settings: NexusGenInputs['UpdateAutoUnitsBuildingSettingsInput']; // UpdateAutoUnitsBuildingSettingsInput!
      villageId: string; // ID!
    }
    updateAutoUnitsSettings: { // args
      settings: NexusGenInputs['UpdateAutoUnitsSettingsInput']; // UpdateAutoUnitsSettingsInput!
      villageId: string; // ID!
    }
    updateAutoUnitsUnitSettings: { // args
      settings: NexusGenInputs['UpdateAutoUnitsUnitSettingsInput']; // UpdateAutoUnitsUnitSettingsInput!
      villageId: string; // ID!
    }
    updateGeneralSettings: { // args
      settings: NexusGenInputs['UpdateGeneralSettingsInput']; // UpdateGeneralSettingsInput!
    }
    updateGeneralVillageSettings: { // args
      settings: NexusGenInputs['UpdateGeneralVillageSettingsInput']; // UpdateGeneralVillageSettingsInput!
      villageId: string; // ID!
    }
    updateGeneralVillageSettingsOrder: { // args
      order: NexusGenEnums['TaskType'][]; // [TaskType!]!
      villageId: string; // ID!
    }
    updateHeroLevelUpItem: { // args
      id: string; // ID!
      item: NexusGenInputs['HeroLevelUpItemInput']; // HeroLevelUpItemInput!
    }
  }
  Query: {
    account: { // args
      id: string; // ID!
    }
    autoAcademySettings: { // args
      villageId: string; // ID!
    }
    autoBuildSettings: { // args
      villageId: string; // ID!
    }
    autoPartySettings: { // args
      villageId: string; // ID!
    }
    autoSmithySettings: { // args
      villageId: string; // ID!
    }
    autoUnitsSettings: { // args
      villageId: string; // ID!
    }
    availableNewBuildings: { // args
      input: NexusGenInputs['AvailableNewBuildingsInput']; // AvailableNewBuildingsInput!
    }
    buildingQueue: { // args
      villageId: string; // ID!
    }
    buildingsInProgress: { // args
      villageId: string; // ID!
    }
    canMoveQueuedBuilding: { // args
      queueId: string; // ID!
      targetQueueId: string; // ID!
      villageId: string; // ID!
    }
    crannyCapacity: { // args
      villageId: string; // ID!
    }
    generalVillageSettings: { // args
      villageId: string; // ID!
    }
    infrastructure: { // args
      villageId: string; // ID!
    }
    isAccountTaken: { // args
      account: NexusGenInputs['AccountInput']; // AccountInput!
    }
    nextTaskExecution: { // args
      task: NexusGenEnums['TaskType']; // TaskType!
    }
    nextVillageTaskExecution: { // args
      task: NexusGenEnums['TaskType']; // TaskType!
      villageId: string; // ID!
    }
    nextVillageTaskExecutions: { // args
      villageId: string; // ID!
    }
    resourceFields: { // args
      villageId: string; // ID!
    }
    unitInfo: { // args
      index: number; // Int!
    }
    unitUpgradeCost: { // args
      level: number; // Int!
      unitIndex: number; // Int!
    }
    village: { // args
      villageId: string; // ID!
    }
  }
  Subscription: {
    autoAcademySettingsUpdated: { // args
      villageId: string; // ID!
    }
    autoBuildSettingsUpdated: { // args
      villageId: string; // ID!
    }
    autoSmithySettingsUnitRemoved: { // args
      villageId: string; // ID!
    }
    autoSmithySettingsUnitUpdated: { // args
      villageId: string; // ID!
    }
    autoSmithySettingsUpdated: { // args
      villageId: string; // ID!
    }
    autoUnitsSettingsUpdated: { // args
      villageId: string; // ID!
    }
    buildingQueueCorrected: { // args
      villageId: string; // ID!
    }
    buildingQueueTimesUpdated: { // args
      villageId: string; // ID!
    }
    buildingsInProgressUpdated: { // args
      villageId: string; // ID!
    }
    generalVillageSettingsUpdated: { // args
      villageId: string; // ID!
    }
    nextTaskExecutionChanged: { // args
      task: NexusGenEnums['TaskType']; // TaskType!
    }
    nextVillageTaskExecutionChanged: { // args
      task: NexusGenEnums['TaskType']; // TaskType!
      villageId: string; // ID!
    }
    onBuildingSpotUpdated: { // args
      villageId: string; // ID!
    }
    onCrannyCapacityUpdated: { // args
      villageId: string; // ID!
    }
    queuedBuildingUpdated: { // args
      villageId: string; // ID!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  LogEntryContent: "AutoBuildLogEntryContent" | "AutoUnitsLogEntryContent" | "ResourceClaimLogEntryContent" | "TextLogEntryContent" | "UnitUpgradeLogEntryContent"
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = keyof NexusGenUnions;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "LogEntryContent";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    resolveType: true
    isTypeOf: false
    __typename: false
  }
}

export interface NexusGenTypes {
  context: ApiContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}